# Programa que, Imprimira os principais valores de vendas da loja Hashtag$Drink do ultimo ano

VendasCoca = 150
VendasPepsi = 130
PrecoUnidadeCoca = 1.50
PrecoUnidadePepsi = 1.50
CustoTotal = 2.500

print(f'Quantia de unidades de coca vendidas: {VendasCoca}')
print(f'Quantia de unidades de pepsi vendidas: {VendasPepsi}')
print(f'Valor por unidades de coca vendidas: {PrecoUnidadeCoca}')
print(f'Valor por unidades de pepso vendidas: {PrecoUnidadePepsi}')
print(f'Custo total da loja vendidas: {CustoTotal}')